[package]
name = "saturn-tauri"
version = "0.1.0"
edition = "2024"
build = "build.rs"
license = "GPL-3.0-only"

[workspace]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
gstreamer = "0.25.3"
gstreamer-pbutils = "0.25.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
saturn-core = { path = "../../crates/saturn-core" }
saturn-render = { path = "../../crates/saturn-render" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tokio = { version = "1", features = ["time"] }
