[package]
name = "project-saturn"
version = "0.1.0"
edition = "2024"
rust-version = "1.92"
description = "A native Linux video editor in development"
license = "GPL-3.0-only"

[dependencies]
gtk = { package = "gtk4", version = "0.11.3", features = ["v4_10"] }
gstreamer = "0.25.3"
gstreamer-pbutils = "0.25.3"
